---
driver:
  name: vagrant
  customize:
    nictype1: 'virtio'

provisioner:
  name: chef_zero

platforms:
  - name: debian8_local
    driver:
      box: debian8_local
  - name: ubuntu/trusty64

suites:
  - name: default
    run_list:
      - recipe[platform_base::default]
    attributes:
